#!/usr/bin/env python3
"""
Blackhearts file-index generator.

Regenerate:   python3 .github/scripts/gen_index.py
Verify only:  python3 .github/scripts/gen_index.py --check
Write only:   python3 .github/scripts/gen_index.py --write

FILE-INDEX.txt lists every file in the repository, one repository-relative
path per line, so that "what is actually in here" is answerable without
guessing and without a network call.

It used to be regenerated by hand. That made the index unreproducible: the
`index` check in validate.py could prove the file was consistent, but
nobody could regenerate it from a clean checkout. A generated artifact that
cannot be regenerated is an artifact nobody can trust after the fact.

This script closes that gap. --check is what CI runs; it exits non-zero if
the committed file differs from what this script would produce, so drift is
impossible to commit by accident.

Rules:
  * One path per line, sorted, repository-relative, forward slashes.
  * FILE-INDEX.txt does not list itself.
  * Skip: .git, __pycache__, and compiled Python (.pyc/.pyo).
  * Skip: anything matched by .gitignore -- an ignored file is not part of
    the repository, so listing it would create a dangling index entry.
  * The header is generated, not hand-maintained, and states the total, so
    the count in the header is a claim that can be checked against the body.

Exit codes:  0 = in sync (or written), 1 = drift, 2 = bad usage.
"""

import os
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
INDEX = os.path.join(REPO, "FILE-INDEX.txt")
SKIP_DIRS = {".git", "__pycache__"}
SKIP_EXT = (".pyc", ".pyo")


def collect():
    """Every file in the working tree except FILE-INDEX.txt itself.

    This deliberately mirrors validate.py's walk_files() semantics rather
    than `git ls-files`. The two must agree, or the generator and the
    validator would disagree about what the repository contains and CI would
    fail on a correctly-regenerated index. In particular this means .gitignore
    is NOT applied here: the validator does not apply it either, and a
    generator that filtered differently from its checker would be a new way
    for the index to lie.

    Tracked files are added on top of the walk, so a file that is committed
    but missing from the working tree is reported as a dangling entry rather
    than silently dropped. That is the behaviour you want: it surfaces a
    deleted file instead of quietly agreeing with the deletion.
    """
    found = set()
    for dp, dn, fn in os.walk(REPO):
        dn[:] = sorted(d for d in dn if d not in SKIP_DIRS)
        for name in fn:
            if name.endswith(SKIP_EXT):
                continue
            rel = os.path.relpath(os.path.join(dp, name), REPO).replace(os.sep, "/")
            if rel != "FILE-INDEX.txt":
                found.add(rel)
    try:
        out = subprocess.run(
            ["git", "-C", REPO, "ls-files", "-z"],
            capture_output=True, text=True, check=True).stdout
        found |= {p for p in out.split("\0") if p and p != "FILE-INDEX.txt"}
    except Exception:
        # git unavailable: the filesystem walk alone is still correct
        pass
    return sorted(found)


def render(paths):
    total = len(paths)
    header = [
        "# Blackhearts file index",
        "#",
        "# Every file in this repository, one repository-relative path per line.",
        "#",
        "# Regenerate:  python3 .github/scripts/gen_index.py --write",
        "# Verify:      python3 .github/scripts/gen_index.py --check",
        "#",
        "# A file that exists but is not listed here, or a listed path that does",
        "# not exist, fails `python3 .github/scripts/validate.py` (check: index)",
        "# and fails this script in CI.",
        "#",
        f"# Total entries: {total}",
        "",
    ]
    return "\n".join(header + paths) + "\n"


def main(argv):
    args = argv[1:]
    if not args:
        args = ["--check"]
    if len(args) > 1 or args[0] not in ("--check", "--write"):
        sys.stderr.write(__doc__)
        return 2

    if args[0] == "--write" and "--allow-dirty" not in args:
        # The index is a claim about the tree; do not record a damaged one.
        sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
        from guard_clean import check
        if check(REPO):
            return 1

    paths = collect()
    want = render(paths)

    if not os.path.isfile(INDEX):
        have = ""
    else:
        with open(INDEX) as fh:
            have = fh.read()

    if have == want:
        print(f"  FILE-INDEX.txt in sync ({len(paths)} entries)")
        return 0

    if args[0] == "--write":
        with open(INDEX, "w") as fh:
            fh.write(want)
        print(f"  FILE-INDEX.txt written ({len(paths)} entries)")
        return 0

    old = len([l for l in have.splitlines() if l.strip() and not l.startswith("#")])
    print(f"  FAIL  index      FILE-INDEX.txt is stale: {old} on disk, "
          f"{len(paths)} expected")
    print("        run:  python3 .github/scripts/gen_index.py --write")
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
