#!/usr/bin/env python3
"""
Regenerate skills/openclaw.example.json5 from the current mirror.

The config is the declared loading policy for the whole vendored catalogue. It
is generated rather than hand-maintained so it cannot drift out of step with the
mirror: every skill name, every group directory, and every agent allowlist is
derived from what is actually on disk.

Run:  python3 .github/scripts/gen_config.py
"""
import os
import re

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MIRROR = os.path.join(REPO, "skills", "third-party", "claude-skills")
OUT = os.path.join(REPO, "skills", "openclaw.example.json5")
COMMIT = "19392f7a08264ed00486a251f5b2098321771f94"

# Loaded but inactive by default: live incident evidence is not covered by
# ordinary testing authorization.
DISABLED = {
    "incident-response":
        "Live incident evidence is not covered by ordinary testing authorization; "
        "enable only with an explicit incident-response engagement record.",
}

PROMOTED = [
    "ai-security", "cloud-security", "dependency-auditor", "red-team",
    "security-pen-testing", "senior-security", "threat-detection",
]


def sh(*a):
    import subprocess
    return subprocess.run(a, capture_output=True, text=True).stdout


def skill_dirs():
    out = []
    for dp, dn, fn in os.walk(MIRROR):
        dn[:] = [d for d in dn if d != "__pycache__"]
        if "SKILL.md" in fn and not os.path.islink(os.path.join(dp, "SKILL.md")):
            out.append(os.path.relpath(dp, MIRROR).replace(os.sep, "/"))
    return sorted(out)


def frontmatter_name(path):
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            lines = fh.read().split("\n")
    except OSError:
        return None
    if not lines or lines[0].strip() != "---":
        return None
    for line in lines[1:]:
        if line.strip() == "---":
            break
        m = re.match(r"^name:\s*(.+?)\s*$", line)
        if m:
            return m.group(1).strip().strip("\"'")
    return None


def main():
    dirs = skill_dirs()
    real = [d for d in dirs
            if not any("/".join(d.split("/")[:i]) in set(dirs)
                       for i in range(1, len(d.split("/"))))]
    names = {}
    for d in real:
        names.setdefault(frontmatter_name(os.path.join(MIRROR, d, "SKILL.md")), d)

    groups = sorted({d.split("/")[0] for d in dirs})
    ncmds = len([f for f in os.listdir(os.path.join(MIRROR, "commands"))
                 if f.endswith(".md")]) if os.path.isdir(os.path.join(MIRROR, "commands")) else 0
    nagents = sum(len(fs) for _, _, fs in os.walk(os.path.join(MIRROR, "agents"))) \
        if os.path.isdir(os.path.join(MIRROR, "agents")) else 0

    A = []
    a = A.append
    a("// Blackhearts — OpenClaw example configuration")
    a("//")
    a("// Valid JSON5. Validate with:")
    a("//   python3 -c \"import json5;json5.load(open('skills/openclaw.example.json5'))\"")
    a("//")
    a(f"// GENERATED by .github/scripts/gen_config.py — do not hand-edit.")
    a(f"// Regenerate after any mirror change so this cannot drift from reality.")
    a("//")
    a(f"// Scope: the complete vendored mirror — {len(dirs)} canonical skill directories,")
    a(f"// {ncmds} slash commands, and {nagents} agent personas, from claude-skills")
    a(f"// @ {COMMIT} (MIT, Alireza Rezvani), plus the mandatory Blackhearts")
    a("// conformance skill. See skills/VENDOR.md for provenance and the audit record.")
    a("//")
    a("// Every vendored area carries a _BLACKHEART-ADAPTER.md recording its audit")
    a("// verdict and its conditions of use. An entry here does NOT authorize that")
    a("// content to touch a target: see the security gate at the bottom, and")
    a("// skills/conformance/SKILL.md.")
    a("")
    a("{")
    a("  skills: {")
    a("    // Load every group directory in the mirror, so nothing is silently")
    a("    // skipped by the six-level discovery depth limit. Upstream nests some")
    a("    // skills deeper than that, e.g. engineering-team/playwright-pro/skills/pw.")
    a("    load: {")
    a("      extraDirs: [")
    entries = [f"'skills/third-party/claude-skills/{g}'" for g in groups]
    # Slash commands and agent personas are not skills; they load from their own
    # directories. Both are inside the array, which is what makes them load.
    a("        // groups")
    for e in entries:
        a(f"        {e},")
    a("        // slash commands")
    a("        'skills/third-party/claude-skills/commands',")
    a("        // agent personas")
    a("        'skills/third-party/claude-skills/agents',")
    a("      ],")
    a("      watch: true,")
    a("    },")
    a("")
    a(f"    // Explicit per-skill policy for the {len(names)} distinct skill names in")
    a(f"    // the mirror. {len(names)} names cover all {len(real)} loadable directories:")
    a(f"    // {len(real) - len(names)} names appear at two upstream paths each (upstream")
    a("    // duplication, e.g. 'handoff' exists under both engineering/ and")
    a("    // productivity/). One entry enables both copies; VENDOR.md maps them.")
    a("    entries: {")
    a("      // --- Layer 0: mandatory, always on ---")
    a("      'blackheart-conformance': { enabled: true },")
    a("")
    a("      // --- Layer 5 promoted security skills (individually audited) ---")
    for n in sorted(DISABLED):
        a(f"      // {DISABLED[n]}")
        a(f"      '{n}': {{ enabled: false }},")
    for n in sorted(PROMOTED):
        if n in names:
            a(f"      '{n}': {{ enabled: true }},")
    a("")
    a(f"      // --- Remaining vendored catalogue ({len(names) - len(PROMOTED) - 1} names) ---")
    a("      // Each has an adapter. Non-PASS audit verdicts are adjudicated in the")
    a("      // adapter, not suppressed.")
    for n in sorted(set(names) - set(PROMOTED) - set(DISABLED)):
        a(f"      '{n}': {{ enabled: true }},")
    a("    },")
    a("")
    a("    // --- Authorization gate ---------------------------------------------")
    a("    // Nothing in this file authorizes scanning, testing, or profiling any")
    a("    // target. A target URL, APK, repository, or test account must be supplied")
    a("    // explicitly by the operator and the engagement recorded, before any")
    a("    // content may act.")
    a("    //")
    a("    // JSON5 carries no executable code, so the gate is declared, not")
    a("    // implemented. These are hard preconditions enforced by")
    a("    // skills/conformance/SKILL.md and by the operator.")
    a("    security: {")
    a("      requireAuthorizedTarget: true,")
    a("      requireEngagementRecord: true,")
    a("      requireAdapter: true,")
    a("      denyTargetsWithoutScope: true,")
    a("      defaultEvidenceStatus: 'UNVERIFIED',")
    a("    },")
    a("  },")
    a("")
    a("  agents: {")
    a("    // Agent profiles inherit the conformance skill. No profile may act on")
    a("    // an unauthorized target regardless of which skills are loaded.")
    a("    //")
    a("    // Vendored agent personas under claude-skills/agents/ are NOT listed")
    a("    // here on purpose. A persona can redefine an agent's identity or widen")
    a("    // its scope; adopting one is an explicit decision, not a default. Where")
    a("    // a persona conflicts with conformance, conformance wins.")
    a("    defaults: { skills: ['blackheart-conformance'] },")
    a("    'security-engineer': {")
    a("      skills: ['blackheart-conformance', 'ai-security', 'cloud-security',")
    a("               'security-pen-testing', 'red-team', 'senior-security',")
    a("               'threat-detection'],")
    a("    },")
    a("    'appsec-reviewer': {")
    a("      skills: ['blackheart-conformance', 'security-pen-testing',")
    a("               'dependency-auditor', 'data-quality-auditor',")
    a("               'api-design-reviewer'],")
    a("    },")
    a("    'incident-responder': {")
    a("      // Requires an explicit incident engagement record; see the entry above.")
    a("      skills: ['blackheart-conformance', 'incident-response', 'senior-secops',")
    a("               'threat-detection'],")
    a("    },")
    a("    'compliance-auditor': {")
    a("      skills: ['blackheart-conformance', 'soc2-audit-prep', 'iso27001-audit-prep',")
    a("               'gdpr-audit-prep', 'compliance-readiness'],")
    a("    },")
    a("  },")
    a("}")
    a("")
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(A))
    print(f"  wrote {os.path.relpath(OUT, REPO)}")
    print(f"  {len(names)} skill names · {len(groups)} group dirs · "
          f"{ncmds} commands · {nagents} agent files")


if __name__ == "__main__":
    main()
